### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: './data/acai_encodings/omniglot_200_train.npz'

### ISSUE THREAD

**Issue by dragen1860** [hsukyle/cactus-maml#1]
Dear author:
In your offered data.tar.gz, I can only find `./data/acai_encodings/omniglot_256_train.npz` but no `./data/acai_encodings/omniglot_200_train.npz` can be found.
```
Traceback (most recent call last):
  File "main.py", line 311, in <module>
    main()
  File "main.py", line 190, in main
    FLAGS.meta_batch_size)
  File "/home/i/meta/cactus-maml/data_generator.py", line 41, in __init__
    get_data(FLAGS.datasource, FLAGS.num_encoding_dims, FLAGS.test_set)
  File "/home/i/meta/cactus-maml/utils.py", line 100, in get_data
    X_train, Y_train, Z_train = get_XYZ(filenames['train'])
  File "/home/i/meta/cactus-maml/utils.py", line 94, in get_XYZ
    data = np.load(filename)
  File "/home/i/conda/lib/python3.6/site-packages/numpy/lib/npyio.py", line 384, in load
    fid = open(file, "rb")
FileNotFoundError: [Errno 2] No such file or directory: './data/acai_encodings/omniglot_200_train.npz'
```

**Comment by kylehkhsu** [comment]
The ACAI embeddings are 256-dimensional. Please see https://github.com/hsukyle/cactus-maml/blob/master/scripts/omniglot_kmeans.sh#L6
